name: Build

on:
  push:
    branches:
      - master
      - dev
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "macos-13", "ubuntu-latest"]
        python-version-major: [3]
        python-version-minor: [9, 10, 11]
    env:
      python-version: ${{ format('{0}.{1}', matrix.python-version-major, matrix.python-version-minor) }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
          cache: "poetry"

      - name: Upgrade Poetry
        run: |
          pip install --quiet --upgrade poetry

      - name: Installation
        run: |
          poetry build -f wheel
          poetry install

      - name: Check
        run: |
          poetry run python -c "import othello"
          poetry run pytest

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*.whl
          draft: false
          prerelease: false
